FROM hasura/graphql-engine:v2.2.1.cli-migrations-v3

COPY ./migrations "/hasura-migrations"
COPY ./metadata "/hasura-metadata"

ENV HASURA_GRAPHQL_METADATA_DATABASE_URL="$HASURA_GRAPHQL_DATABASE_URL"
ENV HASURA_GRAPHQL_DATABASE_URL="$HASURA_GRAPHQL_DATABASE_URL"
ENV PG_DATABASE_URL="$HASURA_GRAPHQL_DATABASE_URL"
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log"
ENV HASURA_GRAPHQL_ADMIN_SECRET="$HASURA_GRAPHQL_ADMIN_SECRET"

EXPOSE 8080
CMD graphql-engine \
    --database-url $HASURA_GRAPHQL_DATABASE_URL \
    serve