name: Publish dev
on:
  push:
    branches: [dev]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install Hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      - name: apply migrations and metadata
        env:
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
        run: |
          hasura metadata apply --endpoint="$HASURA_GRAPHQL_ENDPOINT" --admin-secret="$HASURA_GRAPHQL_ADMIN_SECRET"
          hasura metadata reload --endpoint="$HASURA_GRAPHQL_ENDPOINT" --admin-secret="$HASURA_GRAPHQL_ADMIN_SECRET"
          hasura migrate apply --endpoint="$HASURA_GRAPHQL_ENDPOINT" --admin-secret="$HASURA_GRAPHQL_ADMIN_SECRET"